### ISSUE TITLE
Implement refresh token

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-authentication#1]
https://gist.github.com/vuorinem/6b57225915e00920e3b1

**Comment by alfkonee** [comment]
I'm already working on an implementation of refresh tokens and I'd like to know which repo to create the  PR on when I'm done

**Comment by RWOverdijk** [comment]
@alfkonee That's up to you. I would prefer this one, as I'd otherwise have to port code from the other.

And good to know you're working on it! Someone else is also working on it, perhaps you can [join the chat](https://gitter.im/SpoonX/Dev) and talk? Would be good to have joined efforts I think.

**Comment by alfkonee** [comment]
Ok then this one it is 
PS: already joined the chat if you could tell me who is already working on this it'll be great so that we can pool our efforts

**Comment by alfkonee** [comment]
I'm getting very close to finalizing the main code maybe in the next 36 hrs
Problems: Response interception in fetch client doesn't include request the feature is still in dev with this PR https://github.com/aurelia/fetch-client/pull/34
Hope they add it soon

**Comment by alfkonee** [comment]
Added the response Interceptor Feature to the #31 @RWOverdijk @doktordirk I think this makes it Ok for an initial release of this feature please review the PR

**Comment by doktordirk** [comment]
implement with https://github.com/SpoonX/aurelia-authentication/pull/31

**Comment by rquast** [comment]
Congrats on the new feature!

However, the use of refresh tokens with an SPA (explicit flow), is insecure. It's not only insecure on the client side, it's also insecure on the server side (the authorization code is returned as a query string and may get logged on the server too). Access tokens don't get logged because they're returned in a fragment (which doesn't get logged). All of this is explained in the RFC.

The RFC details this issue - https://tools.ietf.org/html/rfc6749#section-10.5 - and the whole reason why implicit flow was created in the first place.

Other than revocation of long-lived access tokens, reference tokens are one of the ways around this scenario.

**Comment by doktordirk** [comment]
i dont get it. what's about authorization codes? this is access tokens 10.3 and refresh tokens 10.4 here?!

**Comment by rquast** [comment]
You're obtaining refresh tokens because you're using the explicit (authorization code) flow in oauth2.. you're not using implicit flow to get the refresh tokens (because you can't), and you're not obtaining the refresh tokens from a server that did the authorization_code dance with the authorization server.. because you're doing it on the client side with exchangeForToken(). https://github.com/SpoonX/aurelia-authentication/blob/78ec6dd8e4621de76f694d676f73de07f3483faf/src/oAuth1.js#L49

That code exchanges an authorization code (when you use responseType 'code'), for a token (two actually, the refresh and the access tokens)... that's explicit (authorization code) flow.

When you do that call, that's where the problem is that 10.5, 10.6 talks about... e.g.

```
HTTP/1.1 302 Found
     Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA
               &state=xyz
```

^^ From explicit (authorization code) flow - https://tools.ietf.org/html/rfc6749#section-4.1.2

The https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz can get logged in server logs (because server logs record query strings and user-agent history on the client side).

"Since authorization codes are transmitted via user-agent redirections, they could potentially be disclosed through user-agent history and HTTP referrer headers."

Tokens, funnily enough, aren't returned like that, they're returned like this..

```
HTTP/1.1 302 Found
     Location: http://example.com/cb#access_token=2YotnFZFEjr1zCsicMWpAA
               &state=xyz&token_type=example&expires_in=3600
```

The # (fragment) means it doesn't get logged in server logs or appear in user-agent history.

It's really subtle and not well explained.

**Comment by rquast** [comment]
http://stackoverflow.com/questions/35575171/oauth-2-0-authorization-code-flow-using-javascript

http://security.stackexchange.com/questions/67343/secure-rest-api-and-single-page-app-by-using-external-oauth-2-authorization-code

Someone even wrote it in the code somewhere as a comment..

https://github.com/SpoonX/aurelia-authentication/blob/78ec6dd8e4621de76f694d676f73de07f3483faf/src/auth0Lock.js#L75

It's really poorly explained, because it's so complex a topic, and the cause of the problem is so subtle.

**Comment by doktordirk** [comment]
read write a bit an i'm still lost. let's ignore the auth0 for a sec, as that works different. 
so, one common scenario is:
- client: us. has access token for web api and refresh token for authorization server
- user-agent: browser. gets xy from identity server and redirects it to authoritization provider to get it verified and exchanged for access token+refresh token
- identity/authentication provider: facebook, confirms identity, issues xy token
- authorization provider: own express server. confirms authentication with identity provider using xy token. issues access + refresh token. uses refresh token to issue new access token
- web api: own express server. accepts and verifies short term access token to verify authorization

at no time there, the facebook client secret or the own authorization jwt secret is known to the client or the user-agent

**Comment by rquast** [comment]
Okay, I'll ask a simple question then..

Of the 4 different types of OAuth2 flows, what one are you using to get the refresh tokens?

https://tools.ietf.org/html/rfc6749#section-1.3

Which one?

**Comment by doktordirk** [comment]
- authorization code for eg facebook.  the identitiy provider's secret is only on the server and the client never sees the facebook token as that's handled by the server
- or user credentials if authenticating with the server directly

again, i don't know if' that's true also for the Auth0Lock version

**Comment by rquast** [comment]
So if you use authorization code flow, facebook send you back an authorization code, and you send that code back to them to get a token... right? Aurelia auth is the thing that's sending the code back to facebook via the web browser. That's potentially insecure (for the reasons I mentioned earlier) because it's not a _web server_ that's receiving and sending the code back to facebook.

![](http://wiki.smartcommunitylab.it/wikidev/lib/exe/fetch.php?w=600&tok=66eebd&media=aac:flow_authcode.png)

**Comment by rquast** [comment]
http://stackoverflow.com/a/25201443 - "The Authorization-Code-Flow allows for the final auth-token to never reach and never be stored on the machine with the browser/app."

Authorization Code Flow is a server to server flow. It's *not* a server to browser flow.. that's what Implicit Flow is.

**Comment by rquast** [comment]
![](http://oauth2.thephpleague.com/images/grants.svg)
That's how you make the decision on what flow to use. Authorization Code Flow should be authorization server to web server _only_. SPAs should use Implicit Flow or Password Grant _only_.

[http://oauth2.thephpleague.com/authorization-server/which-grant/](http://oauth2.thephpleague.com/authorization-server/which-grant/)

**Comment by rquast** [comment]
Statellizer does it properly.. there's a server script for exchanging the authorization code for a token.

https://github.com/sahat/satellizer/blob/ae7912b8e100a0ec86f66526c0b342b5392189b3/examples/server/node/server.js#L548

Aurelia auth which was supposedly based on Statellizer, (and subsequently, aurelia authentication) doesn't do it properly, they do it in the browser which is wrong for an SPA.

https://github.com/SpoonX/aurelia-authentication/blob/78ec6dd8e4621de76f694d676f73de07f3483faf/src/oAuth1.js#L49

**Comment by doktordirk** [comment]
i haven.t read all you wrote yet, so just a quick note.
 for satellizer you linked the server side. we are doing the client side here. 
maybe see my aurelia-authentication-loopback-sample for the whole deal
and for ours, you linked oauth1. nearly all providers are oauth2 now

**Comment by rquast** [comment]
Nevermind, I don't think you understand what I'm talking about. Maybe it will help others who want to take the time to understand oauth2 security issues.

**Comment by doktordirk** [comment]
i am taking the time. it.s just a lot you send me to read

**Comment by doktordirk** [comment]
well, to conclude this, we as well as aurelia-auth as well as satellizer do the same:

1 open popup with eg `https://www.facebook.com/v2.5/dialog/oauth?client_id=937004143046787&display=popup&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2F&response_type=code&scope=email`
2 in the popup, the user logs into facebook (the authenication provider)
3 on sucess, facebook redirects the popup to eg `http://localhost:9000/?code=***lengthy_code***g#_=_`
4 the popup closes and aurelia-auth gets the code from the redirect query string
5 the code is send to the own authorization server 
6 the server uses the code and sends it together with the client secret (only the authorization server has that) to facebook to validate the identity
7 facebook confirms by sending back the facebock access-token to the authorization server
8 the authorization server can request more info from facebook, eg email and profile
9 the authorization server creates it's own jwt (wihich has nothing to do with the facebook access token. that's only on the authorization server) and sends it's own newly created jwt back the client
10 the client can use the jwt to access the own api server (that api server has no knowledge about facebook. that's only on the authorization server. hence the api server also can access facebook directly neither)
11 the client can use a refresh_token to get from the authorization server a new own jwt for the web server (no facebook involved here)
12 the client might request facebook data by sending a request to the authorization server. the authorization server then can request that info from facebook and send it back to the client

you see, while the (alone useless) code from facebook is exposed to the user-agent, at no time the client has access to the facebook client secret or the facebook access token. that's always on the server only. all requests to facebook (other then login), have to be done via the authorization server, as only he has the access code and the client secret to do so

i hope, your concerns are addressed with that clarification. if you have trouble to find above steps in the code, please tell me. i'll can point you to them

**Comment by doktordirk** [comment]
though now i need to rethink, why the code isn't just send to the server directly, hmm. but maybe it is? thinking...

**Comment by doktordirk** [comment]
http://oauth2.thephpleague.com/authorization-server/which-grant/

> Client Type?
> Depending on whether or not the client is capable of keeping a secret will depend on which grant the client should use.
> If the client is a web application that has a **server side component** then you should implement the **authorization code** grant.

so seems we are on the save side. anyways, this is the client. the client can't be unsave since it is inherently unsave. thus, any sercurity concerns are to be handled on the authentication and authorization server side.
